#pragma once

enum class Region {
    Amsterdam,
    Brazil,
    EU_Central,
    EU_West,
    Frankfurt,
    HongKong,
    Japan,
    London,
    Russia,
    Singapore,
    SouthAfrica,
    Sydney,
    US_Central,
    US_East,
    US_South,
    US_West,
    VIP_Amsterdam,
    VIP_Brazil,
    VIP_EU_Central,
    VIP_EU_West,
    VIP_Frankfurt,
    VIP_HongKong,
    VIP_Japan,
    VIP_London,
    VIP_Russia,
    VIP_Singapore,
    VIP_SouthAfrica,
    VIP_Sydney,
    VIP_US_Central,
    VIP_US_East,
    VIP_US_South,
    VIP_US_West
};