name: Deploy Doxygen Docs

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - ".github/workflows/deploy-docs.yml"
  schedule:
    - cron: '0 12 * * 0'  # Every Sunday at noon UTC

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Doxygen
        run: sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen docs
        working-directory: docs
        run: |
          mkdir -p build
          doxygen Doxyfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          publish_branch: gh-pages
